---

- hosts: web
  become: yes
  tasks:
  -  name: Install  bind9 on Ubuntu
     apt:
        name=bind9
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        bind9 systemd
  handlers:
  - name: bind9 systemd
    systemd:
     name: bind9.service
     enabled: yes
     state: started
