---

- hosts: test 
  become: yes
  tasks:
  -  name: Download kibana
     get_url:
        url: https://www.techplanet.pro/d/kibana-7.17.1-x86_64.rpm
        dest: /tmp/kibana-7.17.1-x86_64.rpm
  -  name: Install kibana
     shell: rpm -i /tmp/kibana-7.17.1-x86_64.rpm
  handlers:
  - name: kibana systemd
    systemd:
     name: kibana.service
     enabled: yes
     state: started

